[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = ["g", "h"]
run = "cd ~/Projects"
desc = "Go to projects"

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = 'plugin cd-build-output'
desc = "Go to build output"

[[mgr.prepend_keymap]]
on = ["g", "j"]
run = 'shell --block -- just --choose'
desc = "Pick recipe"
