# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
schema = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [0, 4, 3]

[opener]
edit = [
    { run = '${EDITOR:-nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'nvim %*', block = true, desc = "nvim", for = "windows" },
]
just = [
    { run = 'just default', desc = "default", block = true },
    { run = 'just rebuild', desc = "rebuild", block = true },
    { run = 'just configure', desc = "configure", block = true },
    { run = 'just build', desc = "build", block = true },
    { run = 'just clean', desc = "clean", block = true },
]
just-folder = [
    { run = 'just %s/default', desc = "default", block = true },
    { run = 'just %s/rebuild', desc = "rebuild", block = true },
    { run = 'just %s/configure', desc = "configure", block = true },
    { run = 'just %s/build', desc = "build", block = true },
    { run = 'just %s/clean', desc = "clean", block = true },
]

[open]
prepend_rules = [
    { url = "*justfile", use = [
        "just",
        "edit",
    ] },
    { mime = "folder/*", use = [
        "edit",
        "just-folder",
    ] },
]

[plugin]
prepend_previewers = [
    { url = "*.dll", run = "inspect-dll" },
    { url = "*.exe", run = "inspect-dll" },
    { url = "*justfile", run = "justfile" },
    { url = "*conanfile.py", run = "conanfile" },
]

# [[plugin.prepend_fetchers]]
# id = "git"
# url = "*"
# run = "git"
#
