# https://just.systems

set shell := ["nu", "--no-config-file", "-c"]
set unstable

# compiler := "clang"

compiler := "msvc"
generator := "ninja-multi"
build_type := "debug"
build_profile := compiler + "-" + generator + "-" + build_type
sources_dir := if path_exists("CMakeLists.txt") == "true" { "." } else { "sources" }
conan_dir := justfile_directory()
build_dir := join( conan_dir, "." + file_name( env('CONAN_HOME') ) )
verbose := "false"

[private]
conan_verbosity := if verbose == "true" { '-c:a tools.build:verbosity=verbose -c:a tools.compilation:verbosity=verbose -v trace ' } else { "" }

[private]
all_build := if build_profile == "default" { "ALL_BUILD" } else { "all" }

[private]
package_info_cmd := "conan inspect " + conan_dir + " --format json | from json"

default: install configure build

[doc('Open commands in mprocs')]
mprocs:
    mprocs --just

[doc('Run the given test, runs all tests by default')]
test TEST='.*': build
    ctest --preset conan-{{ build_type }} --output-on-failure -R {{ TEST }}

[doc('Conan install with the given flags')]
installf *FLAGS:
    conan install {{ conan_dir }} -pr:a {{ build_profile }} -b missing --output-folder {{ build_dir }} {{ conan_verbosity }}{{FLAGS}}

[doc('Get build output')]
@output:
    print {{ build_dir }}

[doc('Conan install with dependencies from cache')]
install: installf

[doc('Conan install with updated dependencies from remotes')]
update: (installf "-u")

[doc('Build the given target, builds all targets by default')]
build TARGET=all_build: devenv
    cmake --build {{ if verbose == "true" { "--verbose " } else { "" } }}--preset conan-{{ build_type }} -t {{ TARGET }}

[doc('Configure project using the conan generated cmake presets')]
configure:
    cmake -S {{ sources_dir }} --preset conan-default -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[doc('Conan create package with the given flags')]
createf *FLAGS:
    conan create {{ conan_dir }} --user cn --channel staging -pr:a {{ build_profile }} -b missing {{ conan_verbosity }}{{FLAGS}}

[doc('Conan create with dependencies from cache')]
create: createf

[doc('Format all files')]
format: devenv
    cmake --build --preset conan-{{ build_type }} -t clangformatfix

[doc('Print package version')]
@version:
    {{ package_info_cmd }} | print $in.version

[doc('Print package name')]
@name:
    {{ package_info_cmd }} | print $in.name

rebuild: clean install configure build

rerebuild: clean update configure build

[doc('Remove cmake cache and configure project using the conan generated cmake presets')]
reconfigure:
    cmake -S {{ sources_dir }} --preset conan-default -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --fresh

[doc('Git clean project directory')]
clean:
    git clean -xdf -e Cargo.lock -e .vscode -e sources -e justfile -e tools -e integration-tests

[private]
devenv:
    nu ([~/Projects .dotfiles cpp setup-cmake.nu] | path join)

[doc('Remove package from cache and conan create with the given flags')]
recreate *FLAGS: cleancache (createf FLAGS)

[doc('Remove package from conan cache')]
cleancache PACKAGE='':
    try { conan remove {{ if PACKAGE == "" { "(" + package_info_cmd + " | get name)" } else { PACKAGE } }} -c }

cleanbuild: (build "clean")

# install1 *FLAGS:
#     conan install . -b missing -if build/msvc17 -g cmake_multi -pr x64d {{ FLAGS }}
#
# configure1:
#     { "version": 4, "vendor": { "conan": {} }, "include": [ "../build/msvc17/generators/CMakePresets.json" ] } | save sources/CMakeUserPresets.json --force
#     cmake -S {{ sources_dir }} --preset default -G "Visual Studio 18 2026" --fresh
#
# build1:
#     cmake --build build/msvc17
#
# conan1 *FLAGS: (install1 FLAGS) configure1 build1
#
# create1 *FLAGS:
#     conan create . cn/staging -b missing {{ FLAGS }}
#
# recreate1 *FLAGS:
#     conan remove {{ file_name(conan_dir) }} -f; conan create . cn/staging -b missing {{ FLAGS }}
