# https://just.systems

set shell := ["nu", "--no-config-file", "-c"]

alias b := build
alias i := install
alias t := test

# compiler := "clang"

compiler := "msvc"
generator := "ninja-multi"
build_type := "debug"
build_profile := compiler + "-" + generator + "-" + build_type
sources_dir := if path_exists("CMakeLists.txt") == "true" { "." } else { "sources" }
conan_dir := justfile_directory()
build_dir := if env_name != "" { projects_dir / ".builds" / file_name(conan_dir) / ( "build_" + env_name ) } else { projects_dir / ".builds" / file_name(conan_dir) }
verbose := "false"
quiet := "false"

[private]
projects_dir := env('projects', '.')
[private]
env_name := if env('CONAN_HOME', '') != "" { file_name(env('CONAN_HOME')) } else { "" }
[private]
cmake_verbosity := if verbose == "true" { "--log-level VERBOSE " } else if quiet == "true" { "--log-level WARNING " } else { "" }
[private]
conan_verbosity := if verbose == "true" { '-c:a tools.build:verbosity=verbose -c:a tools.compilation:verbosity=verbose -v trace ' } else if quiet == "true" { '-c:a tools.cmake:configure_args+=' + quote(trim(cmake_verbosity)) + ' -v warning ' } else { "" }
[private]
build_verbosity := if verbose == "true" { "--verbose " } else { "" }
[private]
all_build := if build_profile == "default" { "ALL_BUILD" } else { "all" }
[private]
package_info_cmd := "conan inspect " + conan_dir + " --format json | from json"

# [private]
# conan_version := `conan --version | split column ' ' _1 _2 version | get version | parse "{major}.{_}.{_}" | get major | print $in --raw`

default: install configure build

[doc('Open commands in mprocs')]
mprocs:
    mprocs --just

[doc('Run the given test, runs all tests by default')]
test TEST='.*': build
    ctest --preset conan-{{ build_type }} --output-on-failure -R {{ TEST }}

[doc('Conan install with the given flags')]
installf *FLAGS:
    conan install {{ conan_dir }} -pr:a {{ build_profile }} -b missing --output-folder {{ build_dir }} {{ conan_verbosity }}{{ FLAGS }}

[doc('Get build output')]
@output:
    print {{ build_dir }}

[doc('Conan install with dependencies from cache')]
install: installf

[doc('Conan install with updated dependencies from remotes')]
update: (installf "-u")

[doc('Build the given target, builds all targets by default')]
build TARGET=all_build: devenv
    cmake --build {{ build_verbosity }}--preset conan-{{ build_type }} -t {{ TARGET }}

[doc('Configure project using the conan generated cmake presets')]
configure:
    cmake -S {{ sources_dir }} {{ cmake_verbosity }}--preset conan-default -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

[doc('Conan create package with the given flags')]
createf *FLAGS:
    conan create {{ conan_dir }} --user cn --channel staging -pr:a {{ build_profile }} -b missing {{ conan_verbosity }}{{ FLAGS }}

[doc('Conan create with dependencies from cache')]
create: createf

[doc('Format all files')]
format: devenv
    cmake --build --preset conan-{{ build_type }} -t clangformatfix

[doc('Print package versions')]
version:
    #! nu
    $env.config.table.show_empty = false;
    let info = {{ package_info_cmd }};
    let current = { source: "current", version: $info.version };
    let remote_and_cache = conan list $info.name -r* -c -v quiet --format json | from json | items { |source, versions| { source: $source, version: ($versions | columns | last | parse "{_}/{version}@cn/staging" | get version | first) } };
    let all = [ $current ] ++ $remote_and_cache;
    $all | each { print $"($in.source): ($in.version)" };

[doc('Print package name')]
@name:
    {{ package_info_cmd }} | print $in.name

rebuild: clean install configure build

rerebuild: clean update configure build

[doc('Remove cmake cache and configure project using the conan generated cmake presets')]
reconfigure:
    cmake -S {{ sources_dir }} --preset conan-default -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --fresh

[doc('Remove build artifacts')]
clean:
    rm {{ build_dir }} -rf --verbose; \
    rm source/CMakeUserPresets.json -f --verbose; \
    rm compile_commands.json -f --verbose; \
    rm CMakeUserPresets.json -f --verbose; \
    rm .clang* -f --verbose; \
    git clean -xdf -e sources -e tools -e integration-tests

[doc('Remove package from cache and conan create with the given flags')]
recreatef *FLAGS: cleancache (createf FLAGS)

[doc('Remove package from cache and conan create with the given flags')]
recreate: recreatef

[doc('Remove package from conan cache')]
cleancache PACKAGE='':
    try { conan remove {{ if PACKAGE == "" { "(" + package_info_cmd + " | get name)" } else { PACKAGE } }} -c }

cleanbuild: (build "clean")

[private]
devenv:
    #! nu
    let root = {{ quote(replace(conan_dir, '\', '/')) }}
    let build_dir = {{ quote(replace(build_dir, '\', '/')) }}
    let links = (glob $"($build_dir)/**/{compile_commands.json}") ++ [$"($env.projects)/cmake-build-smith/additional-files/.clang-format"] ++ [$"($env.projects)/cmake-build-smith/additional-files/.clang-tidy"];
    ls ...$links | each {
        let fileName = $in.name | path basename;
        let filePath = $in.name;
        if (not ( $fileName | path exists )) {
            mklink $fileName $filePath;
        }
    }
    # needed for repos with sources/CMakeLists.txt
    if (not ( $"($root)/CMakeUserPresets.json" | path exists )) {
        let presets = glob $"($build_dir)/**/CMakePresets.json";
        if ($presets | is-not-empty) {
            ls ...$presets | first | $in.name | {
                    version: 4,
                    include: [ $in ]
                }
                | save CMakeUserPresets.json --force
        }
    }

    if (not ( $"($root)/.clangd" | path exists )) {
        let clangd = "CompileFlags:
        Add: ['-std:c++20', '-std:c++latest']";
        $clangd | save .clangd --force
    }

# install1 *FLAGS:
#     conan install {{ conan_dir }} -b missing -if {{ build_dir }}/build/msvc17 -g cmake_multi -pr {{ build_profile }} {{ FLAGS }}
#
# configure1:
#     { "version": 4, "vendor": { "conan": {} }, "include": [ "{{ replace(build_dir, '\', '/') }}/build/msvc17/generators/CMakePresets.json" ] } | save sources/CMakeUserPresets.json --force
#     cmake -S {{ sources_dir }} --preset default -G "Visual Studio 18 2026" --fresh
#
# build1:
#     cmake --build --preset {{ build_type }}
#
# create1:
#     conan create {{ conan_dir }} cn/staging -b missing
#
# cleancache1:
#     conan remove (pwd | path basename) -f
#
# recreate1: cleancache1 create1
