# https://just.systems

set shell := ["nu", "--no-config-file", "-c"]

alias b := build
alias i := install
alias t := test
alias c := configure
alias u := update

# compiler := "clang"

root := replace( justfile_directory(), '\', '/' )
compiler := "msvc"
generator := "ninja-multi"
build_type := "debug"
build_profile := compiler + "-" + generator + "-" + build_type
sources_dir := if path_exists( "CMakeLists.txt" ) == "true" {
        replace( trim_start_match( canonicalize( "." ), '\\?\' ), '\', '/' )
    } else if path_exists( "sources" / "CMakeLists.txt" ) == "true" {
        replace( trim_start_match( canonicalize( "sources" ), '\\?\' ), '\', '/' )
    } else {
        root
    }

build_dir := if env_name != "" { projects_dir / ".builds" / file_name(conan_dir) / ( "build_" + env_name ) } else { projects_dir / ".builds" / file_name(conan_dir) }
verbose := "false"
quiet := "false"

# [private]
# git_branch := `git branch --show-current`
[private]
conan_dir := root
[private]
projects_dir := env('projects', '.')
[private]
env_name := if env('CONAN_HOME', '') != "" { file_name(env('CONAN_HOME')) } else { "" }
[private]
cmake_verbosity := if verbose == "true" { "--log-level VERBOSE " } else if quiet == "true" { "--log-level WARNING " } else { "" }
[private]
conan_verbosity := if verbose == "true" { '-c:a tools.build:verbosity=verbose -c:a tools.compilation:verbosity=verbose -v trace ' } else if quiet == "true" { '-c:a tools.cmake:configure_args+=' + quote(trim(cmake_verbosity)) + ' -v warning ' } else { "" }
[private]
build_verbosity := if verbose == "true" { "--verbose " } else { "" }
[private]
all_build := if build_profile == "default" { "ALL_BUILD" } else { "all" }
[private]
package_info_cmd := "conan inspect " + conan_dir + " --format json | from json"

# [private]
# conan_version := `conan --version | split column ' ' _1 _2 version | get version | parse "{major}.{_}.{_}" | get major | print $in --raw`

default: install configure build

[doc('Conan install with dependencies from cache')]
install: installf

[doc('Conan install with updated dependencies from remotes')]
update: (installf "-u")

[doc('Conan create with dependencies from cache')]
create: createf

[doc('Configure project using the conan generated cmake presets')]
configure: configuref

[doc('Remove cmake cache and configure project using the conan generated cmake presets')]
reconfigure: (configuref "--fresh")

[doc('Build the given target, builds all targets by default')]
build TARGET=all_build: (user_preset conan_dir) devenv
    cmake --build {{ build_verbosity }}--preset conan-{{ build_type }} -t {{ TARGET }}

[doc('Run the given test, runs all tests by default')]
[arg("list", short="l", long="list", value="true")]
[arg("exclude", short="e", long="exclude")]
test list="false" exclude="" TEST='.*': build
    ctest --preset conan-{{ build_type }} {{ if list == "true" { "-N" } else { '-E "' + exclude + '" --output-on-failure -R ' + TEST } }}

[doc('Format all files')]
format: (build "clangformatfix")

[doc('clean install configure build')]
rebuild: clean install configure build

[doc('clean update configure build')]
rerebuild: clean update configure build

[doc('Get build output')]
@output:
    print {{ build_dir }}

[doc('Print current package version')]
@version:
    print ({{ package_info_cmd }} | get version)

[doc('Print package current, remote and cache versions')]
versions:
    #! nu
    $env.config.table.show_empty = false;
    let info = {{ package_info_cmd }};
    let current = { source: "current", version: $info.version };
    let remote_and_cache = conan list $info.name -r* -c -v quiet --format json | from json | items { |source, versions| { source: $source, version: ($versions | columns | last | parse "{_}/{version}@cn/staging" | get version | first) } };
    let all = [ $current ] ++ $remote_and_cache;
    print $info.name
    $all | each { print $"($in.source): ($in.version)" };

[doc('Print package name')]
@name:
    {{ package_info_cmd }} | print $in.name

[doc('Remove install and build artifacts')]
[arg("dry", long="dry", value="true")]
clean dry="false":
    [{{ build_dir }} {{ conan_dir }}/CMakeUserPresets.json {{ sources_dir }}/CMakeUserPresets.json {{ root }}/compile_commands.json ...(glob .clang*) {{ root }}/.cache] \
        | where { $in | path exists } \
        | uniq \
        | each { \
            {{ if dry == 'true' { 'print $"will delete ($in)"' } else { "rm $in --recursive --verbose --trash" } }}; \
        }; \
        {{ if dry == 'true' { 'git clean -nXdf test_package' } else { 'git clean -Xdf test_package' } }}

[doc('Remove package from cache and conan create with the given flags')]
recreate: recreatef

[doc('Remove package from conan cache')]
cleancache PACKAGE='':
    try { conan remove {{ if PACKAGE == "" { "(" + package_info_cmd + " | get name)" } else { PACKAGE } }} -c }

[doc('Remove build artifacts')]
cleanbuild: (build "clean")

[doc('Conan install with the given flags')]
installf *FLAGS:
    conan install {{ conan_dir }} -pr:a {{ build_profile }} -b missing --output-folder {{ build_dir }} {{ conan_verbosity }}{{ FLAGS }}

[doc('Conan create package with the given flags')]
createf *FLAGS:
    conan create {{ conan_dir }} --user cn --channel staging -pr:a {{ build_profile }} -b missing {{ conan_verbosity }}{{ FLAGS }}

[doc('Remove package from cache and conan create with the given flags')]
recreatef *FLAGS: cleancache (createf FLAGS)

[private]
configuref *FLAGS: (user_preset sources_dir) set_sources_dir
    cmake -S {{ sources_dir }} {{ cmake_verbosity }}--preset conan-default -DCMAKE_EXPORT_COMPILE_COMMANDS=ON {{ FLAGS }}

[private]
@set_sources_dir:
    "{{ sources_dir }}" | save {{ build_dir }}/.sources.txt --force

[private]
user_preset FOLDER:
    #! nu
    let build_dir = {{ quote(build_dir) }}
    let sources_dir = {{ quote(sources_dir) }}
    let root = {{ quote(FOLDER) }}
    # needed for repos with sources/CMakeLists.txt
    let presets = glob $"($build_dir)/**/CMakePresets.json";
    if ($presets | is-not-empty) {
        let user_preset = ls ...$presets | first | $in.name | {
                version: 4,
                include: [ $in ]
            };
        rm ( [ $sources_dir CMakeUserPresets.json ] | path join ) --force;
        $user_preset | save ( [ $root CMakeUserPresets.json ] | path join ) --force
    } else {
        print $"(ansi red)[SHMN] No presets found, did you install?(ansi reset)"
        exit 1
    }

[private]
devenv:
    #! nu
    use std null-device
    $env.config.table.show_empty = false;
    let root = {{ quote(conan_dir) }}
    let build_dir = {{ quote(build_dir) }}
    let links = (glob $"($build_dir)/**/{compile_commands.json}") ++ (glob $"($env.projects)/.dotfiles/cpp/.clang*");
    $links
        | each { { file_name: ($in | path basename), file_path: ($in | str replace '/' '\' --all) } }
        | where not ([ $root $it.file_name ] | path join | path exists)
        | each {
            mklink ([ $root $in.file_name ] | path join | str replace '/' '\' --all) $in.file_path;
            attrib +h ([ $root $in.file_name ] | path join | str replace '/' '\' --all) /l o> (null-device)
        }

[doc('List all recipes')]
@list:
    just --list-prefix "" --list-heading $"(just --evaluate)\n" --unsorted --list

install1 *FLAGS:
    conan install {{ conan_dir }} -b missing -if {{ build_dir }}/build/msvc17 -g cmake_multi -pr x64d {{ FLAGS }}

configure1:
    { "version": 4, "vendor": { "conan": {} }, "include": [ "{{ replace(build_dir, '\', '/') }}/build/msvc17/generators/CMakePresets.json" ] } | save sources/CMakeUserPresets.json --force
    cmake -S {{ sources_dir }} --preset default -G "Visual Studio 18 2026" --fresh

build1:
    cmake --build --preset {{ build_type }}

create1 *FLAGS:
    conan create {{ conan_dir }} cn/staging -b missing {{ FLAGS }}

cleancache1:
    conan remove (pwd | path basename) -f

recreate1: cleancache1 create1
