gui:
  theme:
    activeBorderColor:
    - "#33b1ff"
    - bold
    inactiveBorderColor:
    - "#525252"
    searchingActiveBorderColor:
    - "#ff7eb6"
    optionsTextColor:
    - "#33b1ff"
    selectedLineBgColor:
    - "#393939"
    cherryPickedCommitBgColor:
    - "#525252"
    cherryPickedCommitFgColor:
    - "#33b1ff"
    markedBaseCommitFgColor:
    - "#33b1ff"
    unstagedChangesColor:
    - "#ee5396"
    defaultFgColor:
    - "#f2f4f8"
os:
  edit: nvim {{filename}}
notARepository: quit
